name: Terraform Destroy

on: 
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ secrets.GCE_SA_KEY }}"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init and Destroy
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCE_SA_KEY }}
      run: |
        terraform init
        terraform destroy -auto-approve \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="credentials=${{ secrets.GCE_SA_KEY }}"
