name: Terraform Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  terraform:
    name: Terraform Format, Validate and Terratest
    runs-on: ubuntu-latest

    steps:
    - name: google auth
      id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.GCE_SA_KEY }}"

    - name: set up Cloud SDK
      uses: "google-github-actions/setup-gcloud@v1"
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: use gcloud cli
      run: "gcloud info"

    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate
